apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: app
      image: choco85470/myapp:v1
      ports:
        - containerPort: 3000
      env:
        - name: MYSQL_HOST
          value: "127.0.0.1"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "secret"
        - name: MYSQL_DB
          value: "todos"
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret"
        - name: MYSQL_DATABASE
          value: "todos"
      ports:
        - containerPort: 3306
