apiVersion: v1
kind: Pod
metadata:
  name: pingApp
spec:
  containers:
    - name: ping
      image: willfarrell/ping
      env:
        - name: "HOSTNAME"
          value: "8.8.8.8"
        - name: "TIMEOUT"
          value: "300"
